In [2]:
!git clone https://github.com/PhonePe/pulse.git

Cloning into 'pulse'...
Updating files:  13% (1205/9029)
Updating files:  14% (1265/9029)
Updating files:  15% (1355/9029)
Updating files:  16% (1445/9029)
Updating files:  17% (1535/9029)
Updating files:  18% (1626/9029)
Updating files:  19% (1716/9029)
Updating files:  20% (1806/9029)
Updating files:  21% (1897/9029)
Updating files:  22% (1987/9029)
Updating files:  23% (2077/9029)
Updating files:  24% (2167/9029)
Updating files:  25% (2258/9029)
Updating files:  26% (2348/9029)
Updating files:  27% (2438/9029)
Updating files:  28% (2529/9029)
Updating files:  29% (2619/9029)
Updating files:  30% (2709/9029)
Updating files:  30% (2791/9029)
Updating files:  31% (2799/9029)
Updating files:  32% (2890/9029)
Updating files:  33% (2980/9029)
Updating files:  34% (3070/9029)
Updating files:  35% (3161/9029)
Updating files:  36% (3251/9029)
Updating files:  37% (3341/9029)
Updating files:  38% (3432/9029)
Updating files:  39% (3522/9029)
Updating files:  40% (3612/9029)
Updating files:  41% (3702/9029)
Updating files:  41% (3760/9029)
Updating files:  42% (3793/9029)
Updating files:  43% (3883/9029)
Updating files:  44% (3973/9029)
Updating files:  45% (4064/9029)
Updating files:  46% (4154/9029)
Updating files:  47% (4244/9029)
Updating files:  48% (4334/9029)
Updating files:  49% (4425/9029)
Updating files:  50% (4515/9029)
Updating files:  51% (4605/9029)
Updating files:  52% (4696/9029)
Updating files:  53% (4786/9029)
Updating files:  54% (4876/9029)
Updating files:  55% (4966/9029)
Updating files:  56% (5057/9029)
Updating files:  57% (5147/9029)
Updating files:  57% (5186/9029)
Updating files:  58% (5237/9029)
Updating files:  59% (5328/9029)
Updating files:  60% (5418/9029)
Updating files:  61% (5508/9029)
Updating files:  62% (5598/9029)
Updating files:  63% (5689/9029)
Updating files:  63% (5731/9029)
Updating files:  64% (5779/9029)
Updating files:  65% (5869/9029)
Updating files:  66% (5960/9029)
Updating files:  67% (6050/9029)
Updating files:  68% (6140/9029)
Updating files:  69% (6231/9029)
Updating files:  70% (6321/9029)
Updating files:  71% (6411/9029)
Updating files:  72% (6501/9029)
Updating files:  73% (6592/9029)
Updating files:  74% (6682/9029)
Updating files:  75% (6772/9029)
Updating files:  76% (6863/9029)
Updating files:  77% (6953/9029)
Updating files:  78% (7043/9029)
Updating files:  78% (7044/9029)
Updating files:  79% (7133/9029)
Updating files:  80% (7224/9029)
Updating files:  81% (7314/9029)
Updating files:  82% (7404/9029)
Updating files:  83% (7495/9029)
Updating files:  84% (7585/9029)
Updating files:  85% (7675/9029)
Updating files:  86% (7765/9029)
Updating files:  87% (7856/9029)
Updating files:  88% (7946/9029)
Updating files:  89% (8036/9029)
Updating files:  90% (8127/9029)
Updating files:  91% (8217/9029)
Updating files:  92% (8307/9029)
Updating files:  92% (8386/9029)
Updating files:  93% (8397/9029)
Updating files:  94% (8488/9029)
Updating files:  95% (8578/9029)
Updating files:  96% (8668/9029)
Updating files:  97% (8759/9029)
Updating files:  98% (8849/9029)
Updating files:  99% (8939/9029)
Updating files: 100% (9029/9029)
Updating files: 100% (9029/9029), done.

In [46]:
import os
import pandas as pd
import json
from sqlalchemy import create_engine, text

In [ ]:
!pip install sqlalchemy pymysql

In [32]:
from sqlalchemy import create_engine, text

# MySQL connection (encode @ as %40)
engine = create_engine("mysql+pymysql://root:Qwerty%40123@localhost")

# Create connection
with engine.connect() as conn:
    conn.execute(text("CREATE DATABASE IF NOT EXISTS phonepe"))

print("Mission Accomplished")

Mission Accomplished

In [21]:
#1 aggregate > insurance

import os
import json
import pandas as pd

path = r"C:\Users\gopin\OneDrive\Documents\Data_Science\Streamlit Training files\PHONEPE\phpy\Scripts\pulse\data\aggregated\insurance\country\india\state"

agg_ins_state_list = os.listdir(path)


aggr_ins_dic = {'State':[], 'Year':[], 'Quarter':[], 'Transcation_Type':[], 'Transcation_Count':[], 'Transcation_Amount':[]}

for state in agg_ins_state_list:
  agg_ins_year_path = os.path.join(path, state)
  agg_ins_year_list = os.listdir(agg_ins_year_path)

  for year in agg_ins_year_list:
    years_qtr_path = os.path.join(agg_ins_year_path, year)
    years_qtr_list = os.listdir(years_qtr_path)

    for qtr in years_qtr_list:
      qtr_path = os.path.join(years_qtr_path, qtr)
      qtr_file = open(qtr_path, 'r')
      qtr_data = json.load(qtr_file)

      for trans_data in qtr_data['data']['transactionData']:
        aggr_ins_dic['State'].append(state)
        aggr_ins_dic['Year'].append(year)
        aggr_ins_dic['Quarter'].append(int(qtr.strip('.json')))
        aggr_ins_dic['Transcation_Type'].append(trans_data['name'])
        aggr_ins_dic['Transcation_Count'].append(trans_data['paymentInstruments'][0]['count'])
        aggr_ins_dic['Transcation_Amount'].append(trans_data['paymentInstruments'][0]['amount'])


aggr_ins_db = pd.DataFrame(aggr_ins_dic)
aggr_ins_db["State"] = aggr_ins_db["State"].str.replace("-", " ")
aggr_ins_db["State"] = aggr_ins_db["State"].str.title()
aggr_ins_db

,State,Year,Quarter,Transcation_Type,Transcation_Count,Transcation_Amount
0,Andaman & Nicobar Islands,2020,2,Insurance,6,1360.0
1,Andaman & Nicobar Islands,2020,3,Insurance,41,15380.0
2,Andaman & Nicobar Islands,2020,4,Insurance,124,157975.0
3,Andaman & Nicobar Islands,2021,1,Insurance,225,244266.0
4,Andaman & Nicobar Islands,2021,2,Insurance,137,181504.0
...,...,...,...,...,...,...
677,West Bengal,2023,4,Insurance,72712,100365562.0
678,West Bengal,2024,1,Insurance,79576,104987909.0
679,West Bengal,2024,2,Insurance,67048,89476633.0
680,West Bengal,2024,3,Insurance,77158,107451766.0
681,West Bengal,2024,4,Insurance,91719,120602777.0

In [44]:
from sqlalchemy import create_engine

engine = create_engine("mysql+pymysql://root:Qwerty%40123@localhost/phonepe")

aggr_ins_db.to_sql(
    name="aggregated_insurance",
    con=engine,
    if_exists="replace",
    index=False
)


print("aggregated_insurance created Successfuly")

aggregated_insurance created Successfuly

In [22]:
#2 aggregate > transaction

import os
import json
import pandas as pd

aggr_trans_state_path = r"C:\Users\gopin\OneDrive\Documents\Data_Science\Streamlit Training files\PHONEPE\phpy\Scripts\pulse\data\aggregated\transaction\country\india\state"

aggr_trans_state_list = os.listdir(aggr_trans_state_path)

aggr_trans_dic = {'State':[], 'Year':[], 'Quarter':[], 'Transcation_Type':[], 'Transcation_Count':[], 'Transcation_Amount':[]}

for state in aggr_trans_state_list:
  aggr_trans_year_path = os.path.join(aggr_trans_state_path, state)
  aggr_trans_year_list = os.listdir(aggr_trans_year_path)

  for year in aggr_trans_year_list:
    aggr_trans_qtr_path = os.path.join(aggr_trans_year_path, year)
    aggr_trans_qtr_list = os.listdir(aggr_trans_qtr_path)

    for qtr in aggr_trans_qtr_list:
      aggr_trans_qtr_file_path = os.path.join(aggr_trans_qtr_path, qtr)
      aggr_trans_qtr_file = open(aggr_trans_qtr_file_path, 'r')
      aggr_trans_qtr_data = json.load(aggr_trans_qtr_file)

      for trans_data in aggr_trans_qtr_data['data']['transactionData']:
          aggr_trans_dic['State'].append(state.replace("-", " ").title())
          aggr_trans_dic['Year'].append(year)
          aggr_trans_dic['Quarter'].append(int(qtr.strip('.json')))
          aggr_trans_dic['Transcation_Type'].append(trans_data['name'])
          aggr_trans_dic['Transcation_Count'].append(trans_data['paymentInstruments'][0]['count'])
          aggr_trans_dic['Transcation_Amount'].append(trans_data['paymentInstruments'][0]['amount'])


aggr_trans_db = pd.DataFrame(aggr_trans_dic)
aggr_trans_db

,State,Year,Quarter,Transcation_Type,Transcation_Count,Transcation_Amount
0,Andaman & Nicobar Islands,2018,1,Recharge & bill payments,4200,1.845307e+06
1,Andaman & Nicobar Islands,2018,1,Peer-to-peer payments,1871,1.213866e+07
2,Andaman & Nicobar Islands,2018,1,Merchant payments,298,4.525072e+05
3,Andaman & Nicobar Islands,2018,1,Financial Services,33,1.060142e+04
4,Andaman & Nicobar Islands,2018,1,Others,256,1.846899e+05
...,...,...,...,...,...,...
5029,West Bengal,2024,4,Merchant payments,655100809,3.892862e+11
5030,West Bengal,2024,4,Peer-to-peer payments,493217788,1.361927e+12
5031,West Bengal,2024,4,Recharge & bill payments,76043195,5.753406e+10
5032,West Bengal,2024,4,Financial Services,2352084,8.472965e+08
5033,West Bengal,2024,4,Others,421806,5.053641e+08

In [35]:
from sqlalchemy import create_engine

engine = create_engine("mysql+pymysql://root:Qwerty%40123@localhost/phonepe")

aggr_trans_db.to_sql(
    name="aggregated_transaction",
    con=engine,
    if_exists="replace",
    index=False
)

print("aggregated_transaction created Successfuly")

aggregated_transaction created Successfuly

In [23]:
#3 aggregate > User

import os
import json
import pandas as pd

aggr_user_state_path = r"C:\Users\gopin\OneDrive\Documents\Data_Science\Streamlit Training files\PHONEPE\phpy\Scripts\pulse\data\aggregated\user\country\india\state"

aggr_user_state_list = os.listdir(aggr_user_state_path)

aggr_user_dic = {'State':[],
                 'Year':[],
                 'Quarter':[],
                 'Brand':[],
                 'Count':[],
                 'Percentage':[]}


for state in aggr_user_state_list:
  aggr_user_year_path = os.path.join(aggr_user_state_path, state)
  aggr_user_year_list = os.listdir(aggr_user_year_path)

  for year in aggr_user_year_list:
    aggr_user_qtr_path = os.path.join(aggr_user_year_path, year)
    aggr_user_qtr_list = os.listdir(aggr_user_qtr_path)

    for qtr in aggr_user_qtr_list:
      aggr_user_qtr_file_path = os.path.join(aggr_user_qtr_path, qtr)

      with open(aggr_user_qtr_file_path, 'r') as file:
        aggr_user_qtr_data = json.load(file)

      users = aggr_user_qtr_data['data'].get('usersByDevice')

      if users: #Skip Null

        for user_data in users:
            aggr_user_dic['State'].append(state.replace("-", " ").title())
            aggr_user_dic['Year'].append(year)
            aggr_user_dic['Quarter'].append(int(qtr.strip('.json')))
            aggr_user_dic['Brand'].append(user_data['brand'])
            aggr_user_dic['Count'].append(user_data['count'])
            aggr_user_dic['Percentage'].append(user_data['percentage'])


aggr_user_db = pd.DataFrame(aggr_user_dic)
aggr_user_db

                          State  Year  Quarter    Brand    Count  Percentage
0     Andaman & Nicobar Islands  2018        1   Xiaomi     1665    0.247033
1     Andaman & Nicobar Islands  2018        1  Samsung     1445    0.214392
2     Andaman & Nicobar Islands  2018        1     Vivo      982    0.145697
3     Andaman & Nicobar Islands  2018        1     Oppo      501    0.074332
4     Andaman & Nicobar Islands  2018        1  OnePlus      332    0.049258
...                         ...   ...      ...      ...      ...         ...
6727                West Bengal  2022        1   Lenovo   330017    0.015056
6728                West Bengal  2022        1  Infinix   284678    0.012987
6729                West Bengal  2022        1     Asus   280347    0.012790
6730                West Bengal  2022        1    Apple   277752    0.012671
6731                West Bengal  2022        1   Others  2196334    0.100199

[6732 rows x 6 columns]

In [37]:
from sqlalchemy import create_engine

engine = create_engine("mysql+pymysql://root:Qwerty%40123@localhost/phonepe")

aggr_user_db.to_sql(
    name="aggregated_user",
    con=engine,
    if_exists="replace",
    index=False
)

print("aggregated_user created Successfuly")

aggregated_user created Successfuly

In [24]:
#4 map > insurance

import os
import json
import pandas as pd

map_ins_state_path = r"C:\Users\gopin\OneDrive\Documents\Data_Science\Streamlit Training files\PHONEPE\phpy\Scripts\pulse\data\map\insurance\hover\country\india\state"

map_ins_state_list = os.listdir(map_ins_state_path)

map_ins_dic = {'State':[],
                'Year':[],
                'Quarter':[],
                'District_Name':[],
                'Total_Count':[],
                'Total_Amount':[]}

for state in map_ins_state_list:
  map_ins_year_path = os.path.join(map_ins_state_path, state)
  map_ins_year_list = os.listdir(map_ins_year_path)

  for year in map_ins_year_list:
    map_ins_qtr_path = os.path.join(map_ins_year_path, year)
    map_ins_qtr_list = os.listdir(map_ins_qtr_path)

    for qtr in map_ins_qtr_list:
      map_ins_qtr_file_path = os.path.join(map_ins_qtr_path, qtr)

      with open(map_ins_qtr_file_path, 'r') as file:
        map_ins_qtr_data = json.load(file)

        ins = map_ins_qtr_data['data']['hoverDataList']

        if ins:
          for ins_data in ins:
            map_ins_dic['State'].append(state.replace("-", " ").title())
            map_ins_dic['Year'].append(year)
            map_ins_dic['Quarter'].append(int(qtr.strip('.json')))
            map_ins_dic['District_Name'].append(ins_data['name'].strip(' district'))
            map_ins_dic['Total_Count'].append(ins_data['metric'][0]['count'])
            map_ins_dic['Total_Amount'].append(ins_data['metric'][0]['amount'])

map_ins_db = pd.DataFrame(map_ins_dic)
map_ins_db

,State,Year,Quarter,District_Name,Total_Count,Total_Amount
0,Andaman & Nicobar Islands,2020,2,outh andaman,3,795.0
1,Andaman & Nicobar Islands,2020,2,nicoba,3,565.0
2,Andaman & Nicobar Islands,2020,3,north and middle andaman,1,281.0
3,Andaman & Nicobar Islands,2020,3,outh andaman,35,13651.0
4,Andaman & Nicobar Islands,2020,3,nicoba,5,1448.0
...,...,...,...,...,...,...
13871,West Bengal,2024,4,alipurdua,1023,1613143.0
13872,West Bengal,2024,4,paschim bardhaman,4945,7005851.0
13873,West Bengal,2024,4,nadia,3807,5031294.0
13874,West Bengal,2024,4,birbhum,1818,2423290.0
13875,West Bengal,2024,4,purba medinipu,3559,4439061.0

In [38]:
from sqlalchemy import create_engine

engine = create_engine("mysql+pymysql://root:Qwerty%40123@localhost/phonepe")

map_ins_db.to_sql(
    name="map_insurance",
    con=engine,
    if_exists="replace",
    index=False
)

print("map_insurance created Successfuly")

map_insurance created Successfuly

In [ ]:
#5 map > transaction

import os
import json
import pandas as pd

map_trans_state_path = r'C:\Users\gopin\OneDrive\Documents\Data_Science\Streamlit Training files\PHONEPE\phpy\Scripts\pulse\data\map\transaction\hover\country\india\state'

map_trans_state_list = os.listdir(map_trans_state_path)


map_trans_dic = {'State':[],
                'Year':[],
                'Quarter':[],
                'District_Name':[],
                'Total_Count':[],
                'Total_Amount':[]}

for state in map_trans_state_list:
  map_trans_year_path = os.path.join(map_trans_state_path, state)
  map_trans_year_list = os.listdir(map_trans_year_path)

  for year in map_trans_year_list:
    map_trans_qtr_path = os.path.join(map_trans_year_path, year)
    map_trans_qtr_list = os.listdir(map_trans_qtr_path)

    for qtr in map_trans_qtr_list:
      map_trans_qtr_file_path = os.path.join(map_trans_qtr_path, qtr)

      with open(map_trans_qtr_file_path, 'r') as file:
        map_trans_qtr_data = json.load(file)

        ins = map_trans_qtr_data['data']['hoverDataList']

        if ins:
          for trans_data in ins:
            map_trans_dic['State'].append(state.replace("-", " ").title())
            map_trans_dic['Year'].append(year)
            map_trans_dic['Quarter'].append(int(qtr.strip('.json')))
            map_trans_dic['District_Name'].append(trans_data['name'].strip(' district'))
            map_trans_dic['Total_Count'].append(trans_data['metric'][0]['count'])
            map_trans_dic['Total_Amount'].append(trans_data['metric'][0]['amount'])

map_trans_db = pd.DataFrame(map_trans_dic)
map_trans_db

,State,Year,Quarter,District_Name,Total_Count,Total_Amount
0,Andaman & Nicobar Islands,2018,1,north and middle andaman,442,9.316631e+05
1,Andaman & Nicobar Islands,2018,1,outh andaman,5688,1.256025e+07
2,Andaman & Nicobar Islands,2018,1,nicoba,528,1.139849e+06
3,Andaman & Nicobar Islands,2018,2,north and middle andaman,825,1.317863e+06
4,Andaman & Nicobar Islands,2018,2,outh andaman,9395,2.394824e+07
...,...,...,...,...,...,...
20599,West Bengal,2024,4,alipurdua,15875637,2.099251e+10
20600,West Bengal,2024,4,paschim bardhaman,56616799,6.968735e+10
20601,West Bengal,2024,4,nadia,65274337,1.079320e+11
20602,West Bengal,2024,4,birbhum,36905213,5.778701e+10
20603,West Bengal,2024,4,purba medinipu,67833775,1.142771e+11

In [39]:
from sqlalchemy import create_engine

engine = create_engine("mysql+pymysql://root:Qwerty%40123@localhost/phonepe")

map_trans_db.to_sql(
    name="map_transaction",
    con=engine,
    if_exists="replace",
    index=False
)

print("map_transaction created Successfuly")

map_transaction created Successfuly

In [ ]:
#6 map > user

import os
import json
import pandas as pd

map_user_state_path = r'C:\Users\gopin\OneDrive\Documents\Data_Science\Streamlit Training files\PHONEPE\phpy\Scripts\pulse\data\map\user\hover\country\india\state'

map_user_state_list = os.listdir(map_user_state_path)


map_user_dic = {'State':[],
                'Year':[],
                'Quarter':[],
                'District_Name':[],
                'Registered_Users':[],
                'App_Opens':[]}


for state in map_user_state_list:
    map_user_year_path = os.path.join(map_user_state_path, state)
    map_user_year_list = os.listdir(map_user_year_path)

    for year in map_user_year_list:
        map_user_qtr_path = os.path.join(map_user_year_path, year)
        map_user_qtr_list = os.listdir(map_user_qtr_path)

        for qtr in map_user_qtr_list:
            map_user_qtr_file_path = os.path.join(map_user_qtr_path, qtr)

            with open(map_user_qtr_file_path, 'r') as file:
                map_user_qtr_data = json.load(file)

                hover_data = map_user_qtr_data.get('data', {}).get('hoverData', {})

                if hover_data:
                    for district_name, values in hover_data.items():
                        map_user_dic['State'].append(state.replace("-", " ").title())
                        map_user_dic['Year'].append(year)
                        map_user_dic['Quarter'].append(int(qtr.strip('.json')))
                        map_user_dic['District_Name'].append(district_name)
                        map_user_dic['Registered_Users'].append(values.get('registeredUsers', 0))
                        map_user_dic['App_Opens'].append(values.get('appOpens', 0))

map_user_db = pd.DataFrame(map_user_dic)
map_user_db

,State,Year,Quarter,District_Name,Registered_Users,App_Opens
0,Andaman & Nicobar Islands,2018,1,north and middle andaman district,632,0
1,Andaman & Nicobar Islands,2018,1,south andaman district,5846,0
2,Andaman & Nicobar Islands,2018,1,nicobars district,262,0
3,Andaman & Nicobar Islands,2018,2,north and middle andaman district,911,0
4,Andaman & Nicobar Islands,2018,2,south andaman district,8143,0
...,...,...,...,...,...,...
20603,West Bengal,2024,4,alipurduar district,475688,31842355
20604,West Bengal,2024,4,paschim bardhaman district,1468252,80543469
20605,West Bengal,2024,4,nadia district,1861738,98740305
20606,West Bengal,2024,4,birbhum district,1114220,73465525
20607,West Bengal,2024,4,purba medinipur district,1717074,108350777

In [40]:
from sqlalchemy import create_engine

engine = create_engine("mysql+pymysql://root:Qwerty%40123@localhost/phonepe")

map_user_db.to_sql(
    name="map_user",
    con=engine,
    if_exists="replace",
    index=False
)

print("map_user created Successfuly")

map_user created Successfuly

In [ ]:
#7 top > insurance

import os
import json
import pandas as pd

top_ins_state_path = r"C:\Users\gopin\OneDrive\Documents\Data_Science\Streamlit Training files\PHONEPE\phpy\Scripts\pulse\data\top\insurance\country\india\state"

top_ins_state_list = os.listdir(top_ins_state_path)

top_ins_dic = {'State':[],
                'Year':[],
                'Quarter':[],
                'District_Name':[],
                'Total_Count':[],
                'Total_Amount':[]}

for state in top_ins_state_list:
  top_ins_year_path = os.path.join(top_ins_state_path, state)
  top_ins_year_list = os.listdir(top_ins_year_path)

  for year in top_ins_year_list:
    top_ins_qtr_path = os.path.join(top_ins_year_path, year)
    top_ins_qtr_list = os.listdir(top_ins_qtr_path)

    for qtr in top_ins_qtr_list:
      top_ins_qtr_file_path = os.path.join(top_ins_qtr_path, qtr)

      with open(top_ins_qtr_file_path, 'r') as file:
        top_ins_qtr_data = json.load(file)

        ins = top_ins_qtr_data['data']['districts']

        if ins:
          for ins_data in ins:
            top_ins_dic['State'].append(state.replace("-", " ").title())
            top_ins_dic['Year'].append(year)
            top_ins_dic['Quarter'].append(int(qtr.strip('.json')))
            top_ins_dic['District_Name'].append(ins_data['entityName'])
            top_ins_dic['Total_Count'].append(ins_data['metric']['count'])
            top_ins_dic['Total_Amount'].append(ins_data['metric']['amount'])

top_ins_db = pd.DataFrame(top_ins_dic)
top_ins_db

,State,Year,Quarter,District_Name,Total_Count,Total_Amount
0,Andaman & Nicobar Islands,2020,2,nicobars,3,565.0
1,Andaman & Nicobar Islands,2020,2,south andaman,3,795.0
2,Andaman & Nicobar Islands,2020,3,south andaman,35,13651.0
3,Andaman & Nicobar Islands,2020,3,nicobars,5,1448.0
4,Andaman & Nicobar Islands,2020,3,north and middle andaman,1,281.0
...,...,...,...,...,...,...
5603,West Bengal,2024,4,paschim bardhaman,4945,7005851.0
5604,West Bengal,2024,4,paschim medinipur,4155,5405054.0
5605,West Bengal,2024,4,malda,4042,4902098.0
5606,West Bengal,2024,4,nadia,3807,5031294.0
5607,West Bengal,2024,4,purba bardhaman,3595,4482879.0

In [41]:
from sqlalchemy import create_engine

engine = create_engine("mysql+pymysql://root:Qwerty%40123@localhost/phonepe")

top_ins_db.to_sql(
    name="top_insurance",
    con=engine,
    if_exists="replace",
    index=False
)

print("top_insurance created Successfuly")

top_insurance created Successfuly

In [ ]:
#8 top > transaction

import os
import json
import pandas as pd

top_trans_state_path = r"C:\Users\gopin\OneDrive\Documents\Data_Science\Streamlit Training files\PHONEPE\phpy\Scripts\pulse\data\top\transaction\country\india\state"

top_trans_state_list = os.listdir(top_trans_state_path)

top_trans_dic = {'State':[],
                'Year':[],
                'Quarter':[],
                'District_Name':[],
                'Total_Count':[],
                'Total_Amount':[]}

for state in top_trans_state_list:
  top_trans_year_path = os.path.join(top_trans_state_path, state)
  top_trans_year_list = os.listdir(top_trans_year_path)

  for year in top_trans_year_list:
    top_trans_qtr_path = os.path.join(top_trans_year_path, year)
    top_trans_qtr_list = os.listdir(top_trans_qtr_path)

    for qtr in top_trans_qtr_list:
      top_trans_qtr_file_path = os.path.join(top_trans_qtr_path, qtr)

      with open(top_trans_qtr_file_path, 'r') as file:
        top_trans_qtr_data = json.load(file)

        ins = top_trans_qtr_data['data']['districts']

        if ins:
          for trans_data in ins:
            top_trans_dic['State'].append(state.replace("-", " ").title())
            top_trans_dic['Year'].append(year)
            top_trans_dic['Quarter'].append(int(qtr.strip('.json')))
            top_trans_dic['District_Name'].append(trans_data['entityName'])
            top_trans_dic['Total_Count'].append(trans_data['metric']['count'])
            top_trans_dic['Total_Amount'].append(trans_data['metric']['amount'])

top_trans_db = pd.DataFrame(top_trans_dic)
top_trans_db

,State,Year,Quarter,District_Name,Total_Count,Total_Amount
0,Andaman & Nicobar Islands,2018,1,south andaman,5688,1.256025e+07
1,Andaman & Nicobar Islands,2018,1,nicobars,528,1.139849e+06
2,Andaman & Nicobar Islands,2018,1,north and middle andaman,442,9.316631e+05
3,Andaman & Nicobar Islands,2018,2,south andaman,9395,2.394824e+07
4,Andaman & Nicobar Islands,2018,2,nicobars,1120,3.072437e+06
...,...,...,...,...,...,...
8291,West Bengal,2024,4,howrah,67496284,1.025764e+11
8292,West Bengal,2024,4,nadia,65274337,1.079320e+11
8293,West Bengal,2024,4,malda,63424613,1.024212e+11
8294,West Bengal,2024,4,hooghly,59676576,9.071383e+10
8295,West Bengal,2024,4,paschim medinipur,58238212,8.431774e+10

In [42]:
from sqlalchemy import create_engine

engine = create_engine("mysql+pymysql://root:Qwerty%40123@localhost/phonepe")

top_trans_db.to_sql(
    name="top_transaction",
    con=engine,
    if_exists="replace",
    index=False
)

print("top_transaction created Successfuly")

top_transaction created Successfuly

In [ ]:
#9 top > user

import os
import json
import pandas as pd

top_user_state_path = r"C:\Users\gopin\OneDrive\Documents\Data_Science\Streamlit Training files\PHONEPE\phpy\Scripts\pulse\data\top\user\country\india\state"

top_user_state_list = os.listdir(top_user_state_path)

top_user_dic = {'State':[],
                'Year':[],
                'Quarter':[],
                'District_Name':[],
                'Registered_Users':[]}

for state in top_user_state_list:
  top_user_year_path = os.path.join(top_user_state_path, state)
  top_user_year_list = os.listdir(top_user_year_path)

  for year in top_user_year_list:
    top_user_qtr_path = os.path.join(top_user_year_path, year)
    top_user_qtr_list = os.listdir(top_user_qtr_path)

    for qtr in top_user_qtr_list:
      top_user_qtr_file_path = os.path.join(top_user_qtr_path, qtr)

      with open(top_user_qtr_file_path, 'r') as file:
        top_user_qtr_data = json.load(file)

        users = top_user_qtr_data['data']['districts']

        if users:
          for user_data in users:
            top_user_dic['State'].append(state.replace("-", " ").title())
            top_user_dic['Year'].append(year)
            top_user_dic['Quarter'].append(int(qtr.strip('.json')))
            top_user_dic['District_Name'].append(user_data['name'])
            top_user_dic['Registered_Users'].append(user_data['registeredUsers'])


top_user_db = pd.DataFrame(top_user_dic)
top_user_db

,State,Year,Quarter,District_Name,Registered_Users
0,Andaman & Nicobar Islands,2018,1,south andaman,5846
1,Andaman & Nicobar Islands,2018,1,north and middle andaman,632
2,Andaman & Nicobar Islands,2018,1,nicobars,262
3,Andaman & Nicobar Islands,2018,2,south andaman,8143
4,Andaman & Nicobar Islands,2018,2,north and middle andaman,911
...,...,...,...,...,...
8291,West Bengal,2024,4,hooghly,1957356
8292,West Bengal,2024,4,nadia,1861738
8293,West Bengal,2024,4,purba medinipur,1717074
8294,West Bengal,2024,4,paschim medinipur,1522845
8295,West Bengal,2024,4,paschim bardhaman,1468252

In [43]:
from sqlalchemy import create_engine

engine = create_engine("mysql+pymysql://root:Qwerty%40123@localhost/phonepe")

top_user_db.to_sql(
    name="top_user",
    con=engine,
    if_exists="replace",
    index=False
)

print("top_user created Successfuly")

top_user created Successfuly